### ISSUE TITLE
Rename bets

### ISSUE THREAD

**Issue by adrian-golian** [Blef-team/blef_ios_app#48]
Rename bets to follow more standard names, e.g.:
https://en.wikipedia.org/wiki/Poker_probability
https://en.wikipedia.org/wiki/List_of_poker_hands

**Comment by maciej-pomykala** [comment]
What list of names specifically do you have in mind?
A rename could be useful, but for the bet categories most out of tune with poker, flush and straight flush, tuning the names will be tricky - unfortunately we can't say "a king-high straight flush" since in Blef 1) we have to specify which colour it is, making it a long name, and 2) there are two ace-high straights and straight flushes, with varied length.

**Comment by adrian-golian** [comment]
My intention was those:
"Big flush spades" -> "Big straight flush spades"
and
"Colour spades" -> "Flush spades"

**Comment by maciej-pomykala** [comment]
That sounds good

**Comment by adrian-golian** [comment]
We can consider changing
"Small straight"/"Big straight"/"Great straight"
to "Straight (K)"/"Straight (A)"/ "Great straight"
or "Straight (9-K)"/"Straight (10-A)"/ "Straight (9-A)"
but I'm not convinced it's the core issue here.

**Comment by maciej-pomykala** [comment]
Since this is not just about one interface (but useful for rules in general), I propose a discussion in the engine repo (linked above).
